# inserted by test hello-appium/.drone.yml start
# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: hello-appium
type: docker

steps:
- name: test
  image: appium/appium
  commands:
  - echo hello
  - echo world
  - echo $DRONE_BRANCH

# inserted by test hello-appium/.drone.yml end

---

# inserted by test hello-appium-x86-image/.drone.yml start
kind: pipeline
name: hello-appium-x86-image
type: docker

steps:
- name: test
  image: logickee/appium_x86_basic
  commands:
  - echo hello
  - echo world
  - echo $DRONE_BRANCH

# inserted by test hello-appium-x86-image/.drone.yml end
