---
kind: pipeline
type: exec
name: nixos-tests

platform:
  os: linux
  arch: amd64

steps:
- name: test
  commands:
  - nix shell 'nixpkgs#git' -c nix flake check

---
kind: signature
hmac: 5d8d8a905775664e3767957413f19d588cdf550746547ad985ad8254bf265d9e

...
